title: "pLP Replication"
description: "Replication package for 'Nickell Bias in Panel Local Projection: Financial Crises Are Worse Than You Think'"
remote_theme: "just-the-docs/just-the-docs"
color_scheme: light

search_enabled: true
aux_links:
  "View on GitHub":
    - "https://github.com/metricshilab/panel-lp-replication"

plugins:
  - jekyll-remote-theme

footer_content: >
  Licensed under MIT.
